### PR TITLE
Fix: sample code typo

### LINKED ISSUE #1324: Add sample code for BatchGetEffectiveIamPolicy
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
Sample code is missing for get effective iam policies, it's required for GA launch. Here is official doc - https://cloud.google.com/asset-inventory/docs/view-effective-iam-policies

**Describe the solution you'd like**
Add sample code for it.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by haozhang-google**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-asset/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #1324 ☕️

If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).

### CODE REVIEW

**Review by lesv — APPROVED** [review]

**Comment by lesv** [comment]
# Samples
Looks like things took too long. >10m for all tests.  You can fix the timeout in `.github/*` or fix the tests.

Also, I see deprecation warnings in the logs.
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.example.asset.QuickStartIT
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[ERROR] Tests run: 4, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 602.136 s <<< FAILURE! - in com.example.asset.QuickStartIT
[ERROR] com.example.asset.QuickStartIT.testExportAssetBigqueryPerTypeExample  Time elapsed: 283.177 s  <<< ERROR!
java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1543)
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:586)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:66)
	at com.google.api.gax.longrunning.OperationFutureImpl.get(OperationFutureImpl.java:125)
	at com.example.asset.ExportAssetsBigqueryExample.exportBigQuery(ExportAssetsBigqueryExample.java:79)
	at com.example.asset.QuickStartIT.testExportAssetBigqueryPerTypeExample(QuickStartIT.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by lesv** [comment]
@haozhang-google PTAL - Either fix or close

**Comment by haozhang-google** [comment]
There are three tests failed due to no method found:
```
Failures (3):
  JUnit Vintage:AssetServiceClientTest:exportAssetsTest
    MethodSource [className = 'com.google.cloud.asset.v1.AssetServiceClientTest', methodName = 'exportAssetsTest', methodParameterTypes = '']
    => java.lang.RuntimeException: Generated message class "com.google.cloud.asset.v1.ExportAssetsResponse" missing method "getReadTime".
       com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1929)
       com.google.protobuf.GeneratedMessageV3.access$1000(GeneratedMessageV3.java:79)
       com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor$ReflectionInvoker.<init>(GeneratedMessageV3.java:2260)
       com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor.<init>(GeneratedMessageV3.java:2334)
       com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularMessageFieldAccessor.<init>(GeneratedMessageV3.java:3056)
       [...]
     Caused by: java.lang.NoSuchMethodException: com.google.cloud.asset.v1.ExportAssetsResponse.getReadTime()
       java.lang.Class.getMethod(DynamicHub.java:2227)
       com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1926)
       [...]
  JUnit Vintage:AssetServiceClientTest:analyzeIamPolicyLongrunningTest
    MethodSource [className = 'com.google.cloud.asset.v1.AssetServiceClientTest', methodName = 'analyzeIamPolicyLongrunningTest', methodParameterTypes = '']
    => java.util.concurrent.ExecutionException: com.google.api.gax.rpc.UnknownException: Operation with name "analyzeIamPolicyLongrunningTest" succeeded, but encountered a problem unpacking it.
       com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
       com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567)
       com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
       com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:66)
       com.google.api.gax.longrunning.OperationFutureImpl.get(OperationFutureImpl.java:125)
       [...]
     Caused by: com.google.api.gax.rpc.UnknownException: Operation with name "analyzeIamPolicyLongrunningTest" succeeded, but encountered a problem unpacking it.
       com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:80)
       com.google.api.gax.grpc.ProtoOperationTransformers$ResponseTransformer.apply(ProtoOperationTransformers.java:74)
       com.google.api.gax.grpc.ProtoOperationTransformers$ResponseTransformer.apply(ProtoOperationTransformers.java:44)
       com.google.api.core.ApiFutures$ApiFunctionToGuavaFunction.apply(ApiFutures.java:239)
       com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:250)
       [...]
     Caused by: java.lang.RuntimeException: Failed to get default instance for class com.google.cloud.asset.v1.AnalyzeIamPolicyLongrunningResponse
       com.google.protobuf.Internal.getDefaultInstance(Internal.java:374)
       com.google.protobuf.Any.is(Any.java:157)
       com.google.protobuf.Any.unpack(Any.java:175)
       com.google.api.gax.grpc.ProtoOperationTransformers$AnyTransformer.apply(ProtoOperationTransformers.java:132)
       com.google.api.gax.grpc.ProtoOperationTransformers$ResponseTransformer.apply(ProtoOperationTransformers.java:72)
       [...]
     Caused by: java.lang.NoSuchMethodException: com.google.cloud.asset.v1.AnalyzeIamPolicyLongrunningResponse.getDefaultInstance()
       java.lang.Class.getMethod(DynamicHub.java:2227)
       com.google.protobuf.Internal.getDefaultInstance(Internal.java:371)
       [...]
  JUnit Vintage:AssetServiceClientTest:exportAssetsTest
    MethodSource [className = 'com.google.cloud.asset.v1p7beta1.AssetServiceClientTest', methodName = 'exportAssetsTest', methodParameterTypes = '']
    => java.lang.RuntimeException: Generated message class "com.google.cloud.asset.v1p7beta1.ExportAssetsResponse" missing method "getReadTime".
       com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1929)
       com.google.protobuf.GeneratedMessageV3.access$1000(GeneratedMessageV3.java:79)
       com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor$ReflectionInvoker.<init>(GeneratedMessageV3.java:2260)
       com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor.<init>(GeneratedMessageV3.java:2334)
       com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularMessageFieldAccessor.<init>(GeneratedMessageV3.java:3056)
       [...]
     Caused by: java.lang.NoSuchMethodException: com.google.cloud.asset.v1p7beta1.ExportAssetsResponse.getReadTime()
       java.lang.Class.getMethod(DynamicHub.java:2227)
       com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1926)
       [...]
```
But my changes shouldn't affect these three tests.

**Comment by haozhang-google** [comment]
Close this since all sample codes move to [GoogleCloudPlatform/java-docs-samples](https://github.com/GoogleCloudPlatform/java-docs-samples)

**Pull request closed without merging**
